### ISSUE TITLE
How do you configure elasticsearch this way

### ISSUE THREAD

**Issue by onlyahobo** [ahmadimt/springbootes#1]
Hi, I have a problem of configuring the elasticsearch instance created by the application with this attitude - spring boot application. It seems that when you start the app (annotated with @SpringBootApplication) spring will automaticaly run an elasticsearch instance. Can I configure it somehow? Node adresses, ip, etc? I tried to do what is described here http://www.baeldung.com/spring-data-elasticsearch-tutorial:

```
@Bean public ElasticsearchOperations elasticsearchTemplate() {
    Settings.Builder elasticsearchSettings = 
      Settings.settingsBuilder()
      .put("http.enabled", "false")
      .put("path.data", tmpDir.toAbsolutePath().toString()) 
      .put("path.home", "PATH_TO_YOUR_ELASTICSEARCH_DIRECTORY"); 

    return new ElasticsearchTemplate(nodeBuilder()
      .local(true)
      .settings(elasticsearchSettings.build())
      .node()
      .client());
}
```

The problem is that the application ignored this template and its settings and creates its own. How can I address this problem?

Best regards

**Comment by ahmadimtcs** [comment]
@onlyahobo
If you are using Spring Boot, then the clustor name and nodes can be configured in `application.properties` file. Below are the properties for that:

`spring.data.elasticsearch.cluster-name=elasticsearch` # Elasticsearch cluster name.
`spring.data.elasticsearch.cluster-nodes=` # Comma-separated list of cluster node addresses. If not specified, starts a client node.
`spring.data.elasticsearch.repositories.enabled=true`# Enable Elasticsearch repositories.

**Comment by ahmadimt** [comment]
@onlyahobo Does the above solution fix your issue? If not, please create a sample application and share. I'll have a look.
